# Generated by Django 5.1.7 on 2025-04-10 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': [('can_mark_returned', 'Can mark books as returned')]},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_mark_returned', 'Can mark books as returned')]},
        ),
    ]
