# Generated by Django 5.1.7 on 2025-04-21 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_author_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='photo',
        ),
    ]
